# This file was generated by GoReleaser. DO NOT EDIT.
cask "defakto-cli" do
  desc "Defakto CLI"
  homepage "https://defakto.security"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "defakto"

  on_macos do
    on_intel do
      url "https://defakto-releases.s3.us-west-2.amazonaws.com/defakto-cli/v0.0.2/defakto-cli-v0.0.2-darwin-amd64.tar.gz"
      sha256 "698e16821d417f45e88e0917729ce7c19c3327d876950cf793d9ea97656de518"
    end
    on_arm do
      url "https://defakto-releases.s3.us-west-2.amazonaws.com/defakto-cli/v0.0.2/defakto-cli-v0.0.2-darwin-arm64.tar.gz"
      sha256 "9623e78c94fcf692c2dcfcd4656a0f8533f52a51509fa0b7caebff4e705332c3"
    end
  end

  on_linux do
    on_intel do
      url "https://defakto-releases.s3.us-west-2.amazonaws.com/defakto-cli/v0.0.2/defakto-cli-v0.0.2-linux-amd64.tar.gz"
      sha256 "e56dce8751aeb8afc268acd7eee66a715607a50c7822a664bb9fd981480819fe"
    end
    on_arm do
      url "https://defakto-releases.s3.us-west-2.amazonaws.com/defakto-cli/v0.0.2/defakto-cli-v0.0.2-linux-arm64.tar.gz"
      sha256 "8461bf610416c9051d8773c2a913fbf29c2ea32ff80a9e198b58d5159f5f442e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/defakto"]
    end
  end

  # No zap stanza required
end
