# This file was generated by GoReleaser. DO NOT EDIT.
cask "defakto-cli" do
  desc "Defakto CLI"
  homepage "https://defakto.security"
  version "0.35.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "defakto"

  on_macos do
    on_intel do
      url "https://defakto-releases.s3.us-west-2.amazonaws.com/defakto-cli/v0.35.0/defakto-cli-v0.35.0-darwin-amd64.tar.gz"
      sha256 "17d01ed9978ee8a3495d2414c5a2ed498a630d7b076345721ae1cdae4bd1911b"
    end
    on_arm do
      url "https://defakto-releases.s3.us-west-2.amazonaws.com/defakto-cli/v0.35.0/defakto-cli-v0.35.0-darwin-arm64.tar.gz"
      sha256 "66c2ba326bd6a406dc705ac4a7361adc710b40822a468703f4d69690b33ff4b0"
    end
  end

  on_linux do
    on_intel do
      url "https://defakto-releases.s3.us-west-2.amazonaws.com/defakto-cli/v0.35.0/defakto-cli-v0.35.0-linux-amd64.tar.gz"
      sha256 "60a22605d703c405d093d1f09882e53ef9d2b3a0caf81a600be75eca5a8a942f"
    end
    on_arm do
      url "https://defakto-releases.s3.us-west-2.amazonaws.com/defakto-cli/v0.35.0/defakto-cli-v0.35.0-linux-arm64.tar.gz"
      sha256 "b1b1def1bf3cbdaffe0b11568e7f09ded1b96204a1cb4163da2e80ca8047612f"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/defakto"]
    end
  end

  # No zap stanza required
end
