# This file was generated by GoReleaser. DO NOT EDIT.
cask "defakto-cli" do
  desc "Defakto CLI"
  homepage "https://defakto.security"
  version "0.36.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "defakto"

  on_macos do
    on_intel do
      url "https://defakto-releases.s3.us-west-2.amazonaws.com/defakto-cli/v0.36.0/defakto-cli-v0.36.0-darwin-amd64.tar.gz"
      sha256 "3c10c3e74216e065ce3d9520f3e1b9758fd3f6f89244d7c39564e8bd6296da6d"
    end
    on_arm do
      url "https://defakto-releases.s3.us-west-2.amazonaws.com/defakto-cli/v0.36.0/defakto-cli-v0.36.0-darwin-arm64.tar.gz"
      sha256 "24776cc6a7f302413f5523522f5ab3c8ec254d5aeac495c1a8a34b0f6db20770"
    end
  end

  on_linux do
    on_intel do
      url "https://defakto-releases.s3.us-west-2.amazonaws.com/defakto-cli/v0.36.0/defakto-cli-v0.36.0-linux-amd64.tar.gz"
      sha256 "7d7e4713f09874551d9e17f3783937339eb5133b58510e8cde79fd16e6a521d2"
    end
    on_arm do
      url "https://defakto-releases.s3.us-west-2.amazonaws.com/defakto-cli/v0.36.0/defakto-cli-v0.36.0-linux-arm64.tar.gz"
      sha256 "4047cb794ba909b82651f2032def34f6c635cd811b94a4ddc44fcbe8e3780883"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/defakto"]
    end
  end

  # No zap stanza required
end
