# This file was generated by GoReleaser. DO NOT EDIT.
cask "spiffecli" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "f227ec69ada1e0fd076b0c51885e9cdddb5f73f6216cadb892806fb452f5edff"
      url "https://github.com/defakto-security/spiffecli/releases/download/v#{version}/spiffecli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7ec7bdf82cfc5da2a60f9992e6a6074b1ce7a2f7370f574b39737f05b67d426d"
      url "https://github.com/defakto-security/spiffecli/releases/download/v#{version}/spiffecli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "120d342ed3708710f9c461b859a55ad86332687883940b1c5489265d0f689cbc"
      url "https://github.com/defakto-security/spiffecli/releases/download/v#{version}/spiffecli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c1ce974f774924aa608a3097332b5bb7195afe3593630a4a951dce541bee3928"
      url "https://github.com/defakto-security/spiffecli/releases/download/v#{version}/spiffecli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "spiffecli"
  desc "A SPIFFE CLI"
  homepage "https://github.com/defakto-security/spiffecli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spiffecli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spiffecli"]
    end
  end

  # No zap stanza required

end
